language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
  - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $kekstagram_token

  on:
    branch: master
